# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'orangepaper' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for orangepaper

  pod 'Amplitude-iOS', '~> 4.3.1'
  # pod 'react-native-amplitude-analytics', :path => '../node_modules/react-native-amplitude-analytics'

  # pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'
  
  target 'orangepaperTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

